version: '3'
services:
  paperless:
    build: .
    privileged: true
    devices:
      - /dev/fuse
    volumes:
        - /path/to/your/volumes/dir/:/data
    labels:
        - traefik.http.routers.paperless.rule=Host(`paperless.domain.tld`)
        - traefik.http.routers.paperless.tls=true
        - traefik.http.routers.paperless.entrypoints=https_lan
        - traefik.http.routers.paperless.middlewares=authelia
        - traefik.http.services.paperless_service.loadbalancer.server.port=3000
        - traefik.enable=true
    restart: unless-stopped
